<a href="https://colab.research.google.com/github/meeraraju27/Case_Study/blob/main/Numpy_case_study_Meera_Raju.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

###1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [2]:
A1 = np.arange(10,50)
print(A1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
A2 = np.reshape(A1,(4,10))
print (A2)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [11]:
last = A2[:,-1]
print("Last column :",last)

Last column : [19 29 39 49]


###2. Create two 3×3 matrices:
###One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result
-----------------------------------------------------------------

In [27]:
B1 = np.full((3,3),5)
print("B1\n",B1)
B2 = np.arange(1,10).reshape(3,3)
print("B2\n",B2)

B1
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
B2
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
Sum_matrix = B1 + B2
print("Sum_matrix\n",Sum_matrix)

Pdct_matrix = B1 * B2
print("\nPdct_matrix\n",Pdct_matrix)

T_matrix = np.transpose(Pdct_matrix)
print("\nT_matrix\n",T_matrix)


Sum_matrix
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Pdct_matrix
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

T_matrix
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


###3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.


In [32]:
import random

In [37]:
r_array = np.random.randint(10,100,size = 15)
print(r_array)

replaced = r_array > 50           # Boolean mask
r_array[replaced] = -1
print("Modified array:", r_array)

count = np.sum(replaced)
print("Count of values replaced:", count)

[68 49 37 83 95 16 86 48 19 98 52 21 37 83 35]
Modified array: [-1 49 37 -1 -1 16 -1 48 19 -1 -1 21 37 -1 35]
Count of values replaced: 7


###4.Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:

In [40]:
r1_array = np.random.random((5,4))
print(r1_array)

[[0.121003   0.97414355 0.27854337 0.56532593]
 [0.76487362 0.5418977  0.76106741 0.98149433]
 [0.2383731  0.94960683 0.6220087  0.00159972]
 [0.19095723 0.15386812 0.91041404 0.90041614]
 [0.68095362 0.50742509 0.7942478  0.88126521]]


In [42]:
r1_row_sum = np.sum(r1_array,axis = 1)
print("\nrow sums = ",r1_row_sum)

max_row_index = np.argmax(r1_row_sum)
print("\nRow index with max sum = ",max_row_index)
print("\nRow with max sum = ",r1_array[max_row_index])

# Normalize each row
row_min = r1_array.min(axis=1).reshape(-1, 1)
row_max = r1_array.max(axis=1).reshape(-1, 1)

normalized = (r1_array - row_min) / (row_max - row_min)
print("\nNormalized Array:\n", normalized)


row sums =  [1.93901584 3.04933306 1.81158835 2.15565552 2.86389173]

Row index with max sum =  1

Row with max sum =  [0.76487362 0.5418977  0.76106741 0.98149433]

Normalized Array:
 [[0.         1.         0.18465934 0.52080859]
 [0.50722845 0.         0.49857002 1.        ]
 [0.24975908 1.         0.65443495 0.        ]
 [0.04902427 0.         1.         0.98678481]
 [0.46417845 0.         0.76723362 1.        ]]


###5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [45]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
uniqe_arr = np.unique(arr)
print("unique elements : ",uniqe_arr)

# Get unique values and their counts
unique, counts = np.unique(arr, return_counts=True)

# Find elements with count > 1 → duplicates
duplicates = unique[counts > 1]
print("Duplicate elements:", duplicates)


unique elements :  [1 3 5 7 9]
Duplicate elements: [1 3 5]


###6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.


In [47]:
C1 = np.arange(1,37).reshape(6,6)
print("C1\n",C1)

C1
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [55]:
C2 = C1[1:5,1:5]
print("sub matrix = \n",C2)

sub matrix = 
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [56]:
even_numbers = C2[C2 % 2 == 0]
print("Even numbers from the submatrix:", even_numbers)

Even numbers from the submatrix: [ 8 10 14 16 20 22 26 28]


###7. Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)


In [58]:
D1 = np.arange(0,12).reshape(3,4)
print("D1\n",D1)

D1
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
reshaped_2x6  = D1.reshape(2,6)
print("reshaped_2x6","\n",reshaped_2x6)

flattened = D1.flatten()
print("\nFlattened (1D):\n", flattened)

reshaped_4x3 = flattened.reshape(4, 3)
print("\nreshaped_4x3\n",reshaped_4x3)

reshaped_2x6 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened (1D):
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped_4x3
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


###8 . Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]


In [71]:
a = np.array([[1, 2], [3, 4]])
print(a)

new_row = np.array([5,6])

result = np.vstack([a, new_row])
print("\nnew matrix \n" ,result)

[[1 2]
 [3 4]]

new matrix 
 [[1 2]
 [3 4]
 [5 6]]


###9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements


In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c])
print("Joined array:", joined)

reshaped = joined.reshape(3,3)
print("\nReshaped matrix:\n", reshaped)

diagonal = np.diag(reshaped)
print("\nDiagonal elements:", diagonal)

Joined array: [1 2 3 4 5 6 7 8 9]

Reshaped matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal elements: [1 5 9]


###10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [6]:
E1 = np.arange(1,21)
print(E1)

divisible_by_3_or_5 = E1[(E1 % 3 == 0) | (E1 % 5 == 0)]
print("\nValues divisible by 3 or 5:", divisible_by_3_or_5)

count = len(divisible_by_3_or_5)
print("\nCount of values divisible by 3 or 5:", count)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Values divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]

Count of values divisible by 3 or 5: 9
